name: Pre-merge Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing application for NodeJS ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 15]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
        name: Checkout
      - name: Installing node ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Installing dependencies
        run: sudo npm i -g yarn && yarn
      - run: yarn test
        name: 'Testing'
